'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Bluefreeze.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property _11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _110() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_110", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _17() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_17", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _18() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_18", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _19() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_19", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _210() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_210", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _211() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_211", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _212() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_212", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _213() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_213", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _214() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_214", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _215() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_215", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _26() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_26", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _28() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_28", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _29() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_29", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Exit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Exit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property _Next() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Next", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bootlogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bootlogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cancel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clipartsnow_23() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipartsnow_23", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00000() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00000", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00002() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00002", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00003() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00003", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00004() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00004", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00005() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00005", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00006() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00006", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00008() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00008", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00009() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00009", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00010() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00010", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00011() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00011", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00012() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00012", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00013() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00013", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00014() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00014", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00016() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00016", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00017() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00017", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00018() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00018", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00019() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00019", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00020() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00020", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00021() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00021", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00022() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00022", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00023() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00023", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00024() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00024", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00025() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00025", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00026() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00026", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00027() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00027", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00028() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00028", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00029() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00029", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00031() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00031", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00032() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00032", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00033() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00033", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00034() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00034", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00035() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00035", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00036() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00036", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00037() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00037", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00038() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00038", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00039() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00039", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00040() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00040", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00041() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00041", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00042() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00042", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00043() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00043", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00044() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00044", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00045() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00045", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00046() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00046", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00047() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00047", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00048() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00048", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00050() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00050", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00051() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00051", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00052() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00052", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00053() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00053", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00054() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00054", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00055() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00055", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00056() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00056", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00057() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00057", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00058() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00058", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00059() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00059", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00060() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00060", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00061() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00061", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00062() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00062", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00063() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00063", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00064() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00064", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00065() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00065", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00066() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00066", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00067() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00067", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00068() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00068", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00069() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00069", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00070() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00070", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00072() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00072", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00073() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00073", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00074() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00074", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00075() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00075", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00076() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00076", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00077() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00077", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00078() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00078", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00079() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00079", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00080() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00080", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00081() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00081", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00082() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00082", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00083() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00083", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00084() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00084", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00085() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00085", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00086() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00086", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00087() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00087", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00088() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00088", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00089() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00089", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00090() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00090", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00091() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00091", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00092() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00092", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00093() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00093", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00094() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00094", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Comp_2_1_00095() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Comp_2_1_00095", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property connectatv2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("connectatv2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property dfu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dfu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fail() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fail", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property freezy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("freezy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property main() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property normal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("normal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pic() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("pic", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property redsn0w() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("redsn0w", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property release() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("release", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property remote_both() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("remote_both", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property s_irecovery() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("s_irecovery", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property v10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("v10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property V10letfreeze() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("V10letfreeze", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
